# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  git_url =  "git@github.com:givtnl/givt.apps.codesigning.git"
  
  lane :certificates do
      match(type:"appstore", app_identifier: "net.givtapp.ios,net.givtapp.ios.test", git_url: git_url)
  end
  
  desc "Push a new build to Testflight"
  lane :release do
    if git_branch == "main"
      app_identifier = "net.givtapp.ios"
      scheme = "ios Production"
      configuration = "Production"
    else
      app_identifier = "net.givtapp.ios.test"
      scheme = "ios"
      configuration = "Release"
    end
    setup_ci
    sync_code_signing(type: "appstore", readonly: true, app_identifier: app_identifier, git_url: git_url)
    cocoapods
    api_key = app_store_connect_api_key(
        key_id: "KAJ62HWFNH",
        issuer_id: "69a6de8f-dee3-47e3-e053-5b8c7c11a4d1",
        key_content: ENV['APPSTORECONNECT_PRIVATE_KEY']
    )
    increment_build_number(
      xcodeproj: "ios.xcodeproj", 
      build_number: latest_testflight_build_number(api_key: api_key, app_identifier: app_identifier) + 1)
    build_app(workspace: "ios.xcworkspace", scheme: scheme, include_bitcode: true, include_symbols: true, configuration: configuration)
    dsym_zip
    upload_to_testflight(
        app_identifier: app_identifier,
        api_key: api_key,
        skip_waiting_for_build_processing: true
    )
  end
end
