# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to AppCenter"
  lane :release do
    setup_ci
    sync_code_signing(type: "enterprise", readonly: true, app_identifier: "com.givt.iosnativepre")
    cocoapods
    increment_build_number(
      xcodeproj: "ios.xcodeproj",
      build_number: appcenter_fetch_version_number(
        owner_name: "Givt-NL",
        app_name: "Test"
      )["build_number"].to_i + 1)
    build_app(workspace: "ios.xcworkspace", scheme: "ios")
    dsym_zip
    appcenter_upload(
      owner_name: "Givt-NL",
      owner_type: "organization",
      app_name: "Test",
      notify_testers: true
    )
  end
  
  desc "Push a new production build to Testflight"
  lane :production do
    setup_ci
    sync_code_signing(type: "appstore", readonly: true, app_identifier: "net.givtapp.ios")
    cocoapods
    api_key = app_store_connect_api_key(
        key_id: "KAJ62HWFNH",
        issuer_id: "69a6de8f-dee3-47e3-e053-5b8c7c11a4d1",
        key_filepath: "fastlane/AuthKey_KAJ62HWFNH.p8"
    )
    increment_build_number(
      xcodeproj: "ios.xcodeproj", 
      build_number: latest_testflight_build_number(api_key: api_key, app_identifier: "net.givtapp.ios") + 1)
    build_app(workspace: "ios.xcworkspace", scheme: "ios Production", include_bitcode: true)
    dsym_zip
    upload_to_testflight(
        app_identifier: "net.givtapp.ios",
        api_key: api_key
    )
  end
end
